name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: samar12-rad
          template: classic

          base: header, activity, repositories
          languages: yes
          languages.indepth: yes
          languages.limit: 10

          repositories.featured: peer-connect
          repositories.pinned: perfolyze

          activity: yes
          activity.limit: 5

          timezone: Asia/Kolkata
